PREFIX field: <https://catalogue.org/field/>
PREFIX entity: <https://catalogue.org/entity/>

SELECT ?id ?biosampleStatus ?sampleOriginType ?collectionMoment ?collectionDate
WHERE {
  ?res a entity:Biosample ;
       field:id ?id .
  OPTIONAL { ?res field:pathologicalState ?biosampleStatus . }
  OPTIONAL { ?res field:biosampleType ?sampleOriginType . }
  OPTIONAL { ?res field:ageOfIndividualAtCollection ?collectionMoment . }
  OPTIONAL { ?res field:dateOfCollection ?collectionDate . }
}
