PREFIX field: <https://catalogue.org/field/>
PREFIX entity: <https://catalogue.org/entity/>

SELECT ?id ?name ?desc (GROUP_CONCAT(?keyword;separator="|") AS ?keywords)
WHERE {
  ?ds a entity:Dataset ;
      field:id ?id ;
      field:name ?name ;
      field:description ?desc .
  OPTIONAL { ?ds field:keyword ?keyword . }
}
GROUP BY ?id ?name ?desc
