PREFIX field: <https://catalogue.org/field/>
PREFIX entity: <https://catalogue.org/entity/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct: <http://purl.org/dc/terms/>

CONSTRUCT {
  ?ds a dcat:Dataset ;
      dct:identifier ?id ;
      dct:title ?name ;
      dct:description ?desc ;
      dcat:keyword ?keyword .
}
WHERE {
  ?ds a entity:Dataset ;
      field:id ?id ;
      field:name ?name ;
      field:description ?desc .
  OPTIONAL { ?ds field:keyword ?keyword . }
}
