PREFIX field: <https://catalogue.org/field/>
PREFIX entity: <https://catalogue.org/entity/>
PREFIX schema: <https://schema.org/>

CONSTRUCT {
  ?var a schema:PropertyValue ;
       schema:identifier ?id ;
       schema:propertyID ?id ;
       schema:name ?varName ;
       schema:description ?description ;
       schema:unitText ?unitName ;
       schema:minValue ?repeatMin ;
       schema:maxValue ?repeatMax ;
       schema:additionalProperty ?formatProp ;
       schema:additionalProperty ?mappingSyntaxProp ;
       schema:additionalProperty ?mappingMatchProp ;
       schema:additionalProperty ?mappingSourceIdProp ;
       schema:additionalProperty ?mappingSourceVarProp ;
       schema:additionalProperty ?mappingTargetVarProp .

  ?dataset a schema:Dataset ;
           schema:name ?datasetName ;
           schema:identifier ?datasetResourceId ;
           schema:variableMeasured ?var .

  ?formatProp a schema:PropertyValue ;
              schema:name "format" ;
              schema:value ?formatName .
  ?mappingSyntaxProp a schema:PropertyValue ;
                     schema:name "mappingSyntax" ;
                     schema:value ?mappingSyntax .
  ?mappingMatchProp a schema:PropertyValue ;
                    schema:name "mappingMatch" ;
                    schema:value ?mappingMatchName .
  ?mappingSourceIdProp a schema:PropertyValue ;
                       schema:name "mappingSourceId" ;
                       schema:value ?mappingSourceId .
  ?mappingSourceVarProp a schema:PropertyValue ;
                        schema:name "mappingSourceVariable" ;
                        schema:value ?mappingSourceVariableName .
  ?mappingTargetVarProp a schema:PropertyValue ;
                        schema:name "mappingTargetVariable" ;
                        schema:value ?mappingTargetVariableName .
}
WHERE {
  ?var a entity:Variable ;
       field:id ?id ;
       field:name ?name .
  OPTIONAL { ?var field:label ?label . }
  BIND(COALESCE(?label, ?name) AS ?varName)
  OPTIONAL { ?var field:description ?description . }
  OPTIONAL { ?var field:unitName ?unitName . }
  OPTIONAL { ?var field:repeatMin ?repeatMin . }
  OPTIONAL { ?var field:repeatMax ?repeatMax . }
  OPTIONAL { ?var field:formatName ?formatName . }
  OPTIONAL { ?var field:mappingSyntaxes ?mappingSyntax . }
  OPTIONAL { ?var field:mappingMatchNames ?mappingMatchName . }
  OPTIONAL { ?var field:mappingSourceIds ?mappingSourceId . }
  OPTIONAL { ?var field:mappingSourceVariableNames ?mappingSourceVariableName . }
  OPTIONAL { ?var field:mappingTargetVariableNames ?mappingTargetVariableName . }

  OPTIONAL { ?var field:datasetName ?datasetName . }
  OPTIONAL { ?var field:datasetResourceId ?datasetResourceId . }
  OPTIONAL {
    FILTER(BOUND(?datasetName) || BOUND(?datasetResourceId))
    BIND(
      IRI(
        CONCAT(
          "https://catalogue.org/dataset/",
          ENCODE_FOR_URI(COALESCE(STR(?datasetName), STR(?datasetResourceId)))
        )
      ) AS ?dataset
    )
  }

  OPTIONAL { FILTER(BOUND(?formatName)) BIND(BNODE() AS ?formatProp) }
  OPTIONAL { FILTER(BOUND(?mappingSyntax)) BIND(BNODE() AS ?mappingSyntaxProp) }
  OPTIONAL { FILTER(BOUND(?mappingMatchName)) BIND(BNODE() AS ?mappingMatchProp) }
  OPTIONAL { FILTER(BOUND(?mappingSourceId)) BIND(BNODE() AS ?mappingSourceIdProp) }
  OPTIONAL { FILTER(BOUND(?mappingSourceVariableName)) BIND(BNODE() AS ?mappingSourceVarProp) }
  OPTIONAL { FILTER(BOUND(?mappingTargetVariableName)) BIND(BNODE() AS ?mappingTargetVarProp) }
}
