name: ingest-dcat
validate:
  shacl: shacl/dcat.shacl.ttl
  enabled: true
extract:
  sparql: sparql/ingest_dcat_select.sparql
upload:
  table: Resource
  mode: upsert
  id_prefix: import-
  batch_size: 100
